export enum MessageType {
  TOKENS_UPDATED = 'TOKENS_UPDATED',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  USER_ACTIVITY = 'USER_ACTIVITY',
  SESSION_UPDATED = 'SESSION_UPDATED',
  AUTH_STATE_SYNC = 'AUTH_STATE_SYNC' // Add this new type
}